from .admin import ROUTER as admin_router
from .chat import ROUTER as chat_router
from .config import ROUTER as config_router
from .health import ROUTER as health_router
from .insights import ROUTER as insights_router
from .llm import ROUTER as llm_router
from .media import ROUTER as media_router
from .page import ROUTER as page_router
from .sessions import ROUTER as sessions_router
from .status import ROUTER as status_router
from .update import ROUTER as update_router
from .user import ROUTER as user_router
