import {
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconArchive as Archive,
  IconArchiveOff as ArchiveOff,
  IconWaveSine as AudioLines,
  IconBrain as Brain,
  IconCalendarPlus as CalendarPlus,
  IconCheck as Check,
  IconCircleCheck as CheckCircle2,
  IconChevronDown as ChevronDown,
  IconClipboard as Clipboard,
  IconClock as Clock,
  IconCommand as Command,
  IconCopy as Copy,
  IconCpu as Cpu,
  IconDownload as Download,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconPhoto as FileImage,
  IconFileText as FileText,
  IconFolderOpen as FolderOpen,
  IconGlobe as Globe,
  IconHome as Home,
  IconPhoto as ImageIcon,
  IconInfoCircle as Info,
  IconKey as KeyRound,
  IconLink as Link,
  IconList as List,
  IconLoader2 as Loader2,
  IconMessageCircle as MessageCircle,
  IconMessages as Messages,
  IconMessage2 as MessageSquareText,
  IconMicrophone as Mic,
  IconDeviceDesktop as Monitor,
  IconPalette as Palette,
  IconLayoutSidebar as PanelLeft,
  IconPaperclip as Paperclip,
  IconPencil as Pencil,
  IconPhone as Phone,
  IconPinned as Pin,
  IconPinnedOff as PinOff,
  IconPlus as Plus,
  IconRefresh as RefreshCw,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconSend as Send,
  IconSettings as Settings,
  IconShirt as Shirt,
  IconAdjustmentsHorizontal as SlidersHorizontal,
  IconSparkles as Sparkles,
  IconSquare as Square,
  IconTerminal2 as Terminal,
  IconTrash as Trash2,
  IconUsers as Users,
  IconVideo as Video,
  IconX as X,
  IconBolt as Zap,
  IconBoltFilled as ZapFilled
} from '@tabler/icons-react'

export {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveOff,
  AudioLines,
  Brain,
  CalendarPlus,
  Check,
  CheckCircle2,
  ChevronDown,
  Clipboard,
  Clock,
  Command,
  Copy,
  Cpu,
  Download,
  Eye,
  EyeOff,
  FileImage,
  FileText,
  FolderOpen,
  Globe,
  Home,
  ImageIcon,
  Info,
  KeyRound,
  Link,
  List,
  Loader2,
  MessageCircle,
  Messages,
  MessageSquareText,
  Mic,
  Monitor,
  Palette,
  PanelLeft,
  Paperclip,
  Pencil,
  Phone,
  Pin,
  PinOff,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Shirt,
  SlidersHorizontal,
  Sparkles,
  Square,
  Terminal,
  Trash2,
  Users,
  Video,
  X,
  Zap,
  ZapFilled
}

export type { Icon as IconComponent } from '@tabler/icons-react'
