import {
  IconActivity as Activity,
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconArchive as Archive,
  IconArchiveOff as ArchiveOff,
  IconArrowUp as ArrowUp,
  IconArrowUpRight as ArrowUpRight,
  IconAt as AtSign,
  IconWaveSine as AudioLines,
  IconChartBar as BarChart3,
  IconBrain as Brain,
  IconBug as Bug,
  IconCheck as Check,
  IconCircleCheck as CheckCircle2,
  IconChevronDown as ChevronDown,
  IconChevronLeft as ChevronLeft,
  IconChevronRight as ChevronRight,
  IconClipboard as Clipboard,
  IconClock as Clock,
  IconCommand as Command,
  IconCopy as Copy,
  IconCpu as Cpu,
  IconDownload as Download,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconPhoto as FileImage,
  IconFileText as FileText,
  IconFolderOpen as FolderOpen,
  IconGitBranch as GitBranch,
  IconGlobe as Globe,
  IconHash as Hash,
  IconHelpCircle as HelpCircle,
  IconPhoto as ImageIcon,
  IconInfoCircle as Info,
  IconKey as KeyRound,
  IconLayersIntersect2 as Layers3,
  IconLink as Link,
  IconLoader2 as Loader2,
  IconLock as Lock,
  IconLogin as LogIn,
  IconLogout as LogOut,
  IconMessageCircle as MessageCircle,
  IconMessage2 as MessageSquareText,
  IconMicrophone as Mic,
  IconMicrophoneOff as MicOff,
  IconDeviceDesktop as Monitor,
  IconDeviceDesktopAnalytics as MonitorPlay,
  IconMoon as Moon,
  IconDots as MoreHorizontal,
  IconDotsVertical as MoreVertical,
  IconNotebook as NotebookTabs,
  IconPackage as Package,
  IconPalette as Palette,
  IconLayoutBottombar as PanelBottom,
  IconLayoutSidebar as PanelLeft,
  IconPlayerPause as Pause,
  IconPencil as Pencil,
  IconPhone as Phone,
  IconPin as Pin,
  IconPlayerPlay as Play,
  IconPlus as Plus,
  IconRefresh as RefreshCw,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconSend as Send,
  IconSettings as Settings,
  IconSettings2 as Settings2,
  IconAdjustmentsHorizontal as SlidersHorizontal,
  IconSparkles as Sparkles,
  IconSquare as Square,
  IconSteeringWheel as SteeringWheel,
  IconSun as Sun,
  IconTerminal2 as Terminal,
  IconTrash as Trash2,
  IconUsers as Users,
  IconVolume2 as Volume2,
  IconVolumeOff as VolumeX,
  IconTool as Wrench,
  IconX as X,
  IconBolt as Zap,
  IconBoltFilled as ZapFilled
} from '@tabler/icons-react'

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveOff,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  AudioLines,
  BarChart3,
  Brain,
  Bug,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Clock,
  Command,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileImage,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  Hash,
  HelpCircle,
  ImageIcon,
  Info,
  KeyRound,
  Layers3,
  Link,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  MessageCircle,
  MessageSquareText,
  Mic,
  MicOff,
  Monitor,
  MonitorPlay,
  Moon,
  MoreHorizontal,
  MoreVertical,
  NotebookTabs,
  Package,
  Palette,
  PanelBottom,
  PanelLeft,
  Pause,
  Pencil,
  Phone,
  Pin,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  Square,
  SteeringWheel,
  Sun,
  Terminal,
  Trash2,
  Users,
  Volume2,
  VolumeX,
  Wrench,
  X,
  Zap,
  ZapFilled
}

export type { Icon as IconComponent } from '@tabler/icons-react'
