use std::io::Write;
use std::process::Command;

fn main() {
    // -----------------------------------------------------------------
    // 把安装脚本 pin 烘焙到构建产物中。BUILD_PIN_COMMIT / BUILD_PIN_BRANCH 由
    // bootstrap.rs 的 `option_env!()` 取为默认值；优先级 commit > branch。
    // commit pin 默认为关闭（按分支 HEAD 跟随）；发布构建可通过 SPIRITAGENT_BUILD_PIN_COMMIT 烘焙不可变 SHA。
    // 分支 pin 顺序：环境变量 > 当前 checkout HEAD；分支与 commit 都解析不到时打印 warning。
    // 检测到 .git/HEAD 变化时 rerun，避免切换分支后 stale pin。
    // -----------------------------------------------------------------

    let commit = resolve_commit_pin();
    let branch = resolve_branch_pin();

    if let Some(c) = &commit {
        println!("cargo:rustc-env=BUILD_PIN_COMMIT={c}");
        println!(
            "cargo:warning=spiritagent-bootstrap: pinning to commit {}",
            short(c)
        );
    }
    if let Some(b) = &branch {
        println!("cargo:rustc-env=BUILD_PIN_BRANCH={b}");
        match &commit {
            Some(_) => println!("cargo:warning=spiritagent-bootstrap: pinning to branch {b}"),
            None => println!(
                "cargo:warning=spiritagent-bootstrap: following branch {b} HEAD (no commit pin; \
                 set SPIRITAGENT_BUILD_PIN_COMMIT for an immutable pin)"
            ),
        }
    }
    if commit.is_none() && branch.is_none() {
        // 解析失败时明确警告，避免运行时因缺少 pin 直接报错；构建环境很可能配置有误。
        println!(
            "cargo:warning=spiritagent-bootstrap: no pin resolved at build time; binary will fail at runtime without SPIRITAGENT_SETUP_DEV_REPO_ROOT or runtime args"
        );
    }

    // 切换分支 / 显式 commit pin 解析到移动 ref 时 rerun；.git/HEAD 每次提交/切换都会变。
    let git_dir = locate_git_dir();
    if let Some(gd) = &git_dir {
        println!("cargo:rerun-if-changed={}/HEAD", gd.display());
        // .git/HEAD 常指向 ref（如 `ref: refs/heads/xx/yy`），同时监控 ref 自身，便于同一分支新提交也能 rerun。
        if let Ok(head) = std::fs::read_to_string(gd.join("HEAD")) {
            if let Some(rest) = head.trim().strip_prefix("ref: ") {
                println!("cargo:rerun-if-changed={}/{}", gd.display(), rest);
            }
        }
    }
    println!("cargo:rerun-if-env-changed=SPIRITAGENT_BUILD_PIN_COMMIT");
    println!("cargo:rerun-if-env-changed=SPIRITAGENT_BUILD_PIN_BRANCH");

    // -----------------------------------------------------------------
    // Tauri Windows manifest：声明 level="asInvoker"，避免 Windows 的安装器启发式要求 UAC 提权。
    // -----------------------------------------------------------------
    #[cfg(target_os = "windows")]
    let attrs = {
        let manifest = include_str!("spiritagent-setup.manifest");
        let win = tauri_build::WindowsAttributes::new().app_manifest(manifest);
        tauri_build::Attributes::new().windows_attributes(win)
    };

    #[cfg(not(target_os = "windows"))]
    let attrs = tauri_build::Attributes::new();

    tauri_build::try_build(attrs).expect("failed to run tauri-build");

    embed_payload();
}

fn embed_payload() {
    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let payload_dir = manifest_dir.join("../payload");
    if !payload_dir.is_dir() {
        println!("cargo:warning=spiritagent-bootstrap: payload/ not found; skipping resource embedding");
        return;
    }

    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("embedded_resources.rs");
    let mut f = std::fs::File::create(&out_file).unwrap();

    let prefix = relative_path_prefix(&out_dir, &payload_dir);

    writeln!(f, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "const FILES: &[(&str, &[u8])] = &[").unwrap();

    let mut file_count: u32 = 0;
    for entry in walkdir::WalkDir::new(&payload_dir)
        .follow_links(true)
        .sort_by_file_name()
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let abs = entry.path();
        let rel = abs.strip_prefix(&payload_dir).unwrap();
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let include_path = format!("{}{}", prefix, rel_str);
        writeln!(f, "    (r#\"{}\"#, include_bytes!(r#\"{}\"#)),", rel_str, include_path).unwrap();
        file_count += 1;
    }

    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    writeln!(f, r#"
static EXTRACTED_DIR: std::sync::OnceLock<std::path::PathBuf> = std::sync::OnceLock::new();

pub fn extract_resources() -> &'static std::path::Path {{
    EXTRACTED_DIR.get_or_init(|| {{
        let tmp = std::env::temp_dir().join("spiritagent-setup-payload");
        let _ = std::fs::remove_dir_all(&tmp);

        for (rel, data) in FILES {{
            let path = tmp.join(rel);
            if let Some(parent) = path.parent() {{
                std::fs::create_dir_all(parent).unwrap();
            }}
            std::fs::write(&path, data).unwrap();
        }}

        tracing::info!(path = %tmp.display(), count = FILES.len(), "extracted embedded payload");
        tmp
    }}).as_path()
}}
"#).unwrap();

    println!("cargo:rerun-if-changed={}", payload_dir.display());
    println!("cargo:warning=spiritagent-bootstrap: embedded {file_count} payload files");
}

fn relative_path_prefix(from: &std::path::Path, to: &std::path::Path) -> String {
    let from_abs = std::fs::canonicalize(from).unwrap_or_else(|_| from.to_path_buf());
    let to_abs = std::fs::canonicalize(to).unwrap_or_else(|_| to.to_path_buf());

    let from_comps: Vec<_> = from_abs.components().collect();
    let to_comps: Vec<_> = to_abs.components().collect();

    let mut diverge = 0;
    while diverge < from_comps.len() && diverge < to_comps.len() && from_comps[diverge] == to_comps[diverge] {
        diverge += 1;
    }

    let ups = from_comps.len() - diverge;
    let mut prefix = String::new();
    for _ in 0..ups {
        prefix.push_str("../");
    }
    for comp in &to_comps[diverge..] {
        prefix.push_str(&comp.as_os_str().to_string_lossy());
        prefix.push('/');
    }
    prefix
}

fn resolve_commit_pin() -> Option<String> {
    // commit pin 仅在 SPIRITAGENT_BUILD_PIN_COMMIT 显式设置时生效；缺省按分支 HEAD 跟随。
    let requested = std::env::var("SPIRITAGENT_BUILD_PIN_COMMIT").ok()?;
    let requested = requested.trim();
    if requested.is_empty() {
        return None;
    }
    // 把请求（SHA / tag / branch）解析到不可变 SHA，确保烘焙的 pin 可复现；`^{commit}` 用于把 tag 解引用到它指向的提交。
    if let Ok(out) = Command::new("git")
        .args(["rev-parse", "--verify", &format!("{requested}^{{commit}}")])
        .output()
    {
        if out.status.success() {
            if let Ok(s) = String::from_utf8(out.stdout) {
                let s = s.trim().to_string();
                if !s.is_empty() {
                    return Some(s);
                }
            }
        }
    }
    // 仓库外构建时 git 解析可能失败；此时仅当请求本身已像 SHA 才接受，否则直接 panic，避免烘焙进不可解析的 ref。
    if is_sha(requested) {
        return Some(requested.to_string());
    }
    panic!(
        "SPIRITAGENT_BUILD_PIN_COMMIT={requested:?} could not be resolved to a commit \
         (git rev-parse failed and it is not a valid SHA)"
    );
}

/// 判断 `s` 是否看起来像缩写或完整 git SHA（7..=40 个十六进制字符）。
fn is_sha(s: &str) -> bool {
    let len = s.len();
    (7..=40).contains(&len) && s.chars().all(|c| c.is_ascii_hexdigit())
}

fn resolve_branch_pin() -> Option<String> {
    if let Ok(v) = std::env::var("SPIRITAGENT_BUILD_PIN_BRANCH") {
        if !v.trim().is_empty() {
            return Some(v.trim().to_string());
        }
    }
    let out = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8(out.stdout).ok()?.trim().to_string();
    // detached HEAD 返回 "HEAD"，并无有效分支可 pin；只保留 commit pin。
    if s.is_empty() || s == "HEAD" {
        None
    } else {
        Some(s)
    }
}

fn locate_git_dir() -> Option<std::path::PathBuf> {
    let out = Command::new("git")
        .args(["rev-parse", "--git-dir"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8(out.stdout).ok()?.trim().to_string();
    if s.is_empty() {
        return None;
    }
    Some(std::path::PathBuf::from(s))
}

fn short(commit: &str) -> &str {
    if commit.len() >= 12 {
        &commit[..12]
    } else {
        commit
    }
}
