# 每项为 (骨骼名, 父骨骼, 中文说明)
RIG_BONE_HIERARCHIES: dict[str, list[tuple[str, str | None, str]]] = {
    "biped": [
        ("Hips", None, "根骨骼，骨盆中心"),
        ("Spine", "Hips", "下脊柱"),
        ("Spine1", "Spine", "中脊柱"),
        ("Spine2", "Spine1", "上脊柱/胸廓"),
        ("Neck", "Spine2", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "下颌"),
        ("LeftEye", "Head", "左眼"),
        ("RightEye", "Head", "右眼"),
        ("LeftShoulder", "Spine2", "左肩"),
        ("LeftArm", "LeftShoulder", "左大臂"),
        ("LeftForeArm", "LeftArm", "左小臂"),
        ("LeftHand", "LeftForeArm", "左手"),
        ("RightShoulder", "Spine2", "右肩"),
        ("RightArm", "RightShoulder", "右大臂"),
        ("RightForeArm", "RightArm", "右小臂"),
        ("RightHand", "RightForeArm", "右手"),
        ("LeftUpLeg", "Hips", "左大腿"),
        ("LeftLeg", "LeftUpLeg", "左小腿"),
        ("LeftFoot", "LeftLeg", "左脚"),
        ("LeftToeBase", "LeftFoot", "左脚趾"),
        ("RightUpLeg", "Hips", "右大腿"),
        ("RightLeg", "RightUpLeg", "右小腿"),
        ("RightFoot", "RightLeg", "右脚"),
        ("RightToeBase", "RightFoot", "右脚趾"),
    ],
    "quadruped": [
        ("Hips", None, "根骨骼，骨盆中心"),
        ("Spine", "Hips", "前段脊柱"),
        ("Spine1", "Spine", "中段脊柱"),
        ("Spine2", "Spine1", "后段脊柱/肩胛"),
        ("Neck", "Spine2", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "下颌"),
        ("LeftFrontLeg", "Spine2", "左前腿上节"),
        ("LeftFrontKnee", "LeftFrontLeg", "左前腿膝盖"),
        ("LeftFrontFoot", "LeftFrontKnee", "左前脚掌"),
        ("RightFrontLeg", "Spine2", "右前腿上节"),
        ("RightFrontKnee", "RightFrontLeg", "右前腿膝盖"),
        ("RightFrontFoot", "RightFrontKnee", "右前脚掌"),
        ("LeftHindLeg", "Hips", "左后腿上节"),
        ("LeftHindKnee", "LeftHindLeg", "左后腿膝盖"),
        ("LeftHindFoot", "LeftHindKnee", "左后脚掌"),
        ("RightHindLeg", "Hips", "右后腿上节"),
        ("RightHindKnee", "RightHindLeg", "右后腿膝盖"),
        ("RightHindFoot", "RightHindKnee", "右后脚掌"),
        ("Tail", "Hips", "尾巴根"),
        ("Tail1", "Tail", "尾巴中段"),
        ("Tail2", "Tail1", "尾巴尖"),
    ],
    "avian": [
        ("Hips", None, "根骨骼，身体中心"),
        ("Spine", "Hips", "下脊柱"),
        ("Spine1", "Spine", "上脊柱/胸廓"),
        ("Neck", "Spine1", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "喙/下颌"),
        ("LeftWing1", "Spine1", "左翅根/肱骨"),
        ("LeftWing2", "LeftWing1", "左翅中/尺桡骨"),
        ("LeftWing3", "LeftWing2", "左翅尖/手羽"),
        ("RightWing1", "Spine1", "右翅根/肱骨"),
        ("RightWing2", "RightWing1", "右翅中/尺桡骨"),
        ("RightWing3", "RightWing2", "右翅尖/手羽"),
        ("LeftLeg", "Hips", "左腿/股骨"),
        ("LeftFoot", "LeftLeg", "左脚/跗蹠"),
        ("RightLeg", "Hips", "右腿/股骨"),
        ("RightFoot", "RightLeg", "右脚/跗蹠"),
        ("Tail1", "Hips", "尾羽根"),
        ("Tail2", "Tail1", "尾羽中"),
        ("Tail3", "Tail2", "尾羽尖"),
    ],
    "serpentine": [
        ("Hips", None, "根骨骼，身体中心"),
        ("Spine", "Hips", "脊柱 1"),
        ("Spine1", "Spine", "脊柱 2"),
        ("Spine2", "Spine1", "脊柱 3"),
        ("Spine3", "Spine2", "脊柱 4"),
        ("Spine4", "Spine3", "脊柱 5"),
        ("Spine5", "Spine4", "脊柱 6"),
        ("Spine6", "Spine5", "脊柱 7"),
        ("Spine7", "Spine6", "脊柱 8"),
        ("Spine8", "Spine7", "脊柱 9"),
        ("Spine9", "Spine8", "脊柱 10"),
        ("Neck", "Spine9", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "下颌"),
        ("Tail1", "Hips", "尾巴 1"),
        ("Tail2", "Tail1", "尾巴 2"),
        ("Tail3", "Tail2", "尾巴 3"),
        ("Tail4", "Tail3", "尾巴 4"),
        ("Tail5", "Tail4", "尾巴 5"),
    ],
    "aquatic": [
        ("Hips", None, "根骨骼，身体中心"),
        ("Spine", "Hips", "前段脊柱"),
        ("Spine1", "Spine", "中段脊柱"),
        ("Spine2", "Spine1", "后段脊柱"),
        ("Neck", "Spine2", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "嘴/下颌"),
        ("TopFin", "Spine2", "背鳍"),
        ("BottomFin", "Spine2", "腹鳍"),
        ("LeftFin", "Spine2", "左侧鳍/胸鳍"),
        ("RightFin", "Spine2", "右侧鳍/胸鳍"),
        ("Tail1", "Hips", "尾柄"),
        ("Tail2", "Tail1", "尾干"),
        ("Tail3", "Tail2", "尾鳍上"),
        ("Tail4", "Tail3", "尾鳍下"),
    ],
    "hexapod": [
        ("Hips", None, "根骨骼，胸部中心"),
        ("Spine", "Hips", "前胸"),
        ("Spine1", "Spine", "中胸"),
        ("Spine2", "Spine1", "后胸"),
        ("Neck", "Spine2", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "口器/下颌"),
        ("LeftAntenna", "Head", "左触角"),
        ("RightAntenna", "Head", "右触角"),
        ("LeftFrontLeg", "Spine", "左前腿上节"),
        ("LeftFrontKnee", "LeftFrontLeg", "左前腿膝节"),
        ("LeftFrontFoot", "LeftFrontKnee", "左前腿脚节"),
        ("LeftMidLeg", "Spine1", "左中腿上节"),
        ("LeftMidKnee", "LeftMidLeg", "左中腿膝节"),
        ("LeftMidFoot", "LeftMidKnee", "左中腿脚节"),
        ("LeftHindLeg", "Spine2", "左后腿上节"),
        ("LeftHindKnee", "LeftHindLeg", "左后腿膝节"),
        ("LeftHindFoot", "LeftHindKnee", "左后腿脚节"),
        ("RightFrontLeg", "Spine", "右前腿上节"),
        ("RightFrontKnee", "RightFrontLeg", "右前腿膝节"),
        ("RightFrontFoot", "RightFrontKnee", "右前腿脚节"),
        ("RightMidLeg", "Spine1", "右中腿上节"),
        ("RightMidKnee", "RightMidLeg", "右中腿膝节"),
        ("RightMidFoot", "RightMidKnee", "右中腿脚节"),
        ("RightHindLeg", "Spine2", "右后腿上节"),
        ("RightHindKnee", "RightHindLeg", "右后腿膝节"),
        ("RightHindFoot", "RightHindKnee", "右后腿脚节"),
        ("Tail1", "Hips", "腹部尾节 1"),
        ("Tail2", "Tail1", "腹部尾节 2"),
    ],
    "octopod": [
        ("Hips", None, "根骨骼，身体中心"),
        ("Spine", "Hips", "下躯干"),
        ("Spine1", "Spine", "中躯干"),
        ("Spine2", "Spine1", "上躯干"),
        ("Neck", "Spine2", "颈部"),
        ("Head", "Neck", "头部"),
        ("Jaw", "Head", "口器/喙"),
        ("LeftFrontLeg", "Hips", "左侧第 1 触手"),
        ("LeftMidFrontLeg", "Hips", "左侧第 2 触手"),
        ("LeftMidBackLeg", "Hips", "左侧第 3 触手"),
        ("LeftBackLeg", "Hips", "左侧第 4 触手"),
        ("RightFrontLeg", "Hips", "右侧第 1 触手"),
        ("RightMidFrontLeg", "Hips", "右侧第 2 触手"),
        ("RightMidBackLeg", "Hips", "右侧第 3 触手"),
        ("RightBackLeg", "Hips", "右侧第 4 触手"),
        ("Tail1", "Hips", "尾部/漏斗"),
    ],
}


def get_bone_hierarchy(rig_type: str) -> list[tuple[str, str | None, str]]:
    return RIG_BONE_HIERARCHIES.get(rig_type, RIG_BONE_HIERARCHIES["biped"])


def format_bone_tree(rig_type: str) -> str:
    bones = get_bone_hierarchy(rig_type)
    children: dict[str | None, list[tuple[str, str]]] = {}
    for name, parent, desc in bones:
        children.setdefault(parent, []).append((name, desc))

    lines: list[str] = []

    def _render(parent: str | None, indent: str) -> None:
        for name, desc in children.get(parent, []):
            lines.append(f"{indent}{name}  ({desc})")
            _render(name, indent + "    ")

    _render(None, "")
    return "\n".join(lines)


def bone_names(rig_type: str) -> set[str]:
    return {name for name, _, _ in get_bone_hierarchy(rig_type)}
