export const EMOTION_MAP: Record<string, { label: string; icon: string }> = {
  happy: { label: '开心愉悦', icon: '😊' },
  excited: { label: '兴奋雀跃', icon: '✨' },
  curious: { label: '充满好奇', icon: '🧐' },
  grateful: { label: '心怀感激', icon: '💖' },
  playful: { label: '顽皮逗趣', icon: '😜' },
  proud: { label: '自信自豪', icon: '🌟' },
  smug: { label: '有点得意', icon: '😏' },
  shy: { label: '害羞腼腆', icon: '😳' },
  relieved: { label: '安心放松', icon: '😌' },
  concerned: { label: '关切担忧', icon: '🥺' },
  confused: { label: '略带疑惑', icon: '🤔' },
  surprised: { label: '感到惊讶', icon: '😮' },
  embarrassed: { label: '不好意思', icon: '😅' },
  apologetic: { label: '抱歉内疚', icon: '🙇' },
  sad: { label: '有些低落', icon: '😢' },
  lonely: { label: '稍感孤单', icon: '🌧️' },
  bored: { label: '百无聊赖', icon: '🥱' },
  sleepy: { label: '昏昏欲睡', icon: '😴' },
  pout: { label: '气鼓鼓中', icon: '😤' },
  angry: { label: '有些生气', icon: '💢' },
  scared: { label: '受到惊吓', icon: '😨' }
}
